In [1]:
import pandas as pd
import numpy as np
from IPython.display import display, HTML
import matplotlib.pyplot as plt
import matplotlib.pylab as pltl
import tradingeconomics as te
import json

te.login()

'You are logged in as a guest:guest'

In [2]:
te.getIndicatorData(country=['united states', 'china'], output_type='df')

,Country,Category,LatestValue,LatestValueDate,Source,Unit,CategoryGroup,Frequency,PreviousValue,PreviousValueDate
0,United States,ADP Employment Change,275.00,2019-04-30T00:00:00,"Automatic Data Processing, Inc.",Thousand,Labour,Monthly,151.00,2019-03-31T00:00:00
1,United States,API Crude Oil Stock Change,2.40,2019-05-17T00:00:00,American Petroleum Institute (API),BBL/1Million,Business,Weekly,8.60,2019-05-10T00:00:00
2,United States,Asylum Applications,7267.00,2018-09-30T00:00:00,United Nations Refugee Agency,Persons,Government,Monthly,7682.00,2018-08-31T00:00:00
3,United States,Average Hourly Earnings,0.20,2019-04-30T00:00:00,U.S. Bureau of Labor Statistics,percent,Labour,Monthly,0.20,2019-03-31T00:00:00
4,United States,Average Weekly Hours,34.40,2019-04-30T00:00:00,U.S. Bureau of Labor Statistics,Hours,Labour,Monthly,34.50,2019-03-31T00:00:00
5,China,Balance of Trade,138.34,2019-04-30T00:00:00,General Administration of Customs,USD HML,Trade,Monthly,324.19,2019-03-31T00:00:00
6,United States,Balance of Trade,-50000.00,2019-03-31T00:00:00,U.S. Census Bureau,USD Million,Trade,Monthly,-49300.00,2019-02-28T00:00:00
7,China,Bank Lending Rate,4.35,2019-04-30T00:00:00,People's Bank of China,percent,Consumer,Monthly,4.35,2019-03-31T00:00:00
8,United States,Bank Lending Rate,5.50,2019-04-30T00:00:00,Federal Reserve,percent,Consumer,Monthly,5.50,2019-03-31T00:00:00
9,United States,Bankruptcies,22157.00,2019-03-31T00:00:00,Administrative Office of the U.S. Courts,Companies,Business,Quarterly,22232.00,2018-12-31T00:00:00

In [3]:
def on_message(ws, message):
  print json.loads(message)
  #te.subscribe('calendar')
   # te.run(on_message)

SyntaxError: invalid syntax (<ipython-input-3-430064eb63d1>, line 2)

In [4]:
e.subscribe('calendar')

NameError: name 'e' is not defined

In [5]:
te.run(on_message)

NameError: name 'on_message' is not defined

In [6]:
#getforecastData for country
te.getForecastData(country='china',output_type='df')

,Country,Category,LatestValue,LatestValueDate,YearEnd,YearEnd2,YearEnd3,q1,q1_date,q2,q2_date,q3,q3_date,q4,q4_date
0,China,Balance of Trade,138.34,2019-04-30T00:00:00,550.00,130.00,110.00,370.00,2019-06-30T00:00:00,470.00,2019-09-30T00:00:00,550.00,2019-12-31T00:00:00,150.00,2020-03-31T00:00:00
1,China,Bank Lending Rate,4.35,2019-04-30T00:00:00,4.35,4.35,4.35,4.35,2019-06-30T00:00:00,4.35,2019-09-30T00:00:00,4.35,2019-12-31T00:00:00,4.35,2020-03-31T00:00:00
2,China,Banks Balance Sheet,1020.00,2019-04-30T00:00:00,1200.00,1300.00,1800.00,1700.00,2019-06-30T00:00:00,1500.00,2019-09-30T00:00:00,1200.00,2019-12-31T00:00:00,1900.00,2020-03-31T00:00:00
3,China,Business Confidence,50.10,2019-04-30T00:00:00,50.90,50.50,51.00,50.00,2019-06-30T00:00:00,51.00,2019-09-30T00:00:00,50.90,2019-12-31T00:00:00,49.70,2020-03-31T00:00:00
4,China,Cash Reserve Ratio,13.50,2019-05-31T00:00:00,12.50,12.00,12.00,12.75,2019-06-30T00:00:00,12.75,2019-09-30T00:00:00,12.50,2019-12-31T00:00:00,12.00,2020-03-31T00:00:00
5,China,Composite Pmi,52.70,2019-04-30T00:00:00,51.00,51.40,51.60,51.70,2019-06-30T00:00:00,52.50,2019-09-30T00:00:00,51.00,2019-12-31T00:00:00,50.00,2020-03-31T00:00:00
6,China,Consumer Confidence,124.10,2019-03-31T00:00:00,118.00,115.00,110.00,121.00,2019-06-30T00:00:00,120.00,2019-09-30T00:00:00,118.00,2019-12-31T00:00:00,116.00,2020-03-31T00:00:00
7,China,Consumer Price Index CPI,102.50,2019-04-30T00:00:00,103.84,105.91,107.93,103.73,2019-06-30T00:00:00,104.45,2019-09-30T00:00:00,103.84,2019-12-31T00:00:00,104.35,2020-03-31T00:00:00
8,China,Consumer Spending,317509.70,2017-12-31T00:00:00,336878.00,356417.00,376376.00,327511.00,2019-06-30T00:00:00,327353.00,2019-09-30T00:00:00,336878.00,2019-12-31T00:00:00,336560.00,2020-03-31T00:00:00
9,China,Core Consumer Prices,101.70,2019-04-30T00:00:00,103.84,105.71,107.50,103.63,2019-06-30T00:00:00,103.53,2019-09-30T00:00:00,103.84,2019-12-31T00:00:00,103.73,2020-03-31T00:00:00

In [7]:
#getforecastdata  for many countries
te.getForecastData(country=['united states','china'], output_type='df')

AttributeError: 'list' object has no attribute 'strip'

In [8]:
#Forecasted values for more than one indicator. 
te.getForecastData(indicator= ['gdp', 'population'], output_type='df')

AttributeError: 'list' object has no attribute 'strip'

In [9]:
#Forecasted values for several countries and indicators. 
te.getForecastData(country=['united states', 'china'], indicator=['gdp', 'population'], output_type='df')

AttributeError: 'list' object has no attribute 'strip'

In [10]:
te.getForecastData(country=['united states', 'china'], indicator=['gdp', 'population'], output_type='df')

AttributeError: 'list' object has no attribute 'strip'

In [11]:
#To get stock market index data:
te.getMarketsData(marketsField='index', output_type='df')

,Symbol,Ticker,Name,Country,Date,Last,Group,URL,Importance,DailyChange,...,MonthlyPercentualChange,YearlyChange,YearlyPercentualChange,YTDChange,YTDPercentualChange,yesterday,lastWeek,lastMonth,lastYear,startYear
0,MSETOP:IND,MSETOP,MSE TOP 20,Mongolia,2019-05-17T00:00:00,20246.6300,Asia,/mongolia/stock-market,999,58.1600,...,1.5765,448.9200,2.2675,-1422.3900,-6.5642,20188.4700,20248.24,19932.4000,19797.7100,21669.0200
1,CRSMBCT:IND,CRSMBCT,BCT Corp,Costa Rica,2019-05-27T00:00:00,10143.5700,,/costa-rica/stock-market,1000,13.6900,...,-0.0021,-2749.4700,-21.3252,-1390.1300,-12.0528,10129.8800,10143.58,10143.7800,12893.0400,11533.7000
2,ADR:IND,ADR,NYSE International,United States,2019-05-28T00:00:00,5262.9800,America G20 Major,/adr:ind,20,-34.1100,...,-4.8041,-310.0500,-5.5634,358.6400,7.3127,5297.0900,5336.48,5528.5800,5573.0300,4904.3400
3,BGSMDC:IND,BOTSWANASTOMAR,Gaborone,Botswana,2019-05-28T00:00:00,7727.0800,Africa,/botswana/stock-market,999,0.0000,...,-1.7311,-812.3400,-9.5128,-136.1100,-1.7310,7727.0800,7658.48,7863.2000,8539.4200,7863.1900
4,BLOM:IND,LEBANONSTOMAR,Blom,Lebanon,2019-05-28T00:00:00,866.3163,Asia,/lebanon/stock-market,930,-0.0292,...,-4.4123,-237.0101,-21.4814,-110.4384,-11.3067,866.3455,871.20,906.3048,1103.3264,976.7547
5,BSX:IND,BSX,BSX,Bermuda,2019-05-28T00:00:00,2210.0700,America,/bermuda/stock-market,999,0.0000,...,-6.2238,-474.3300,-17.6699,250.7000,12.7949,2210.0700,2300.94,2356.7500,2684.4000,1959.3700
6,BVPSBVPS:IND,PANAMASTOMAR,BVPSI,Panama,2019-05-28T00:00:00,439.4100,America,/panama/stock-market,920,-0.4100,...,0.2418,-36.1000,-7.5918,-11.5200,-2.5547,439.8200,438.14,438.3500,475.5100,450.9300
7,BVQA:IND,ECUADORSTOARKET,Ecuador General Index,Ecuador,2019-05-28T00:00:00,1349.7500,America,/ecuador/stock-market,66,8.6500,...,-1.0404,33.7300,2.5630,-54.8700,-3.9064,1341.1000,1343.58,1363.9400,1316.0200,1404.6200
8,DARSDSEI:IND,DARSDSEI,DSEI,Tanzania,2019-05-28T00:00:00,1852.8900,Africa,/tanzania/stock-market,880,-41.4800,...,-5.8256,-463.8800,-20.0227,-179.5800,-8.8356,1894.3700,1874.64,1967.5100,2316.7700,2032.4700
9,DHAKA:IND,BANGLADESHSTOMAR,Bangladesh DSE General Index,Bangladesh,2019-05-28T00:00:00,5328.7600,,/dhaka:ind,161,75.2200,...,2.9621,-66.9900,-1.2415,-136.4900,-2.4974,5253.5400,5236.84,5175.4600,5395.7500,5465.2500

In [12]:
#To get stock market data filtered by symbol:
te.getMarketsBySymbol(symbols='indu:ind')

,Symbol,Ticker,Name,Country,Date,Type,decimals,Last,MarketCap,URL,...,YearlyPercentualChange,YTDChange,YTDPercentualChange,yesterday,lastWeek,lastMonth,lastYear,startYear,ISIN,LastUpdate
0,INDU:IND,INDU,Dow Jones,United States,2019-05-29T14:33:00,index,0.0,25200.42,None,/united-states/stock-market,...,2.1593,1854.18,7.9421,25347.77,25776.61,26592.91,24667.78,23346.24,None,2019-05-29T14:35:00

In [13]:
#To get stock market data filtered by symbols:
te.getMarketsBySymbol(symbols=['aapl:us', 'indu:ind'], output_type='df')

,Symbol,Ticker,Name,Country,Date,Type,decimals,Last,MarketCap,URL,...,YearlyPercentualChange,YTDChange,YTDPercentualChange,yesterday,lastWeek,lastMonth,lastYear,startYear,ISIN,LastUpdate
0,AAPL:US,AAPL,Apple,United States,2019-05-29T14:33:00,stocks,2.0,179.04,1.064612e+09,/aapl:us,...,-4.5934,33.04,22.6301,178.23,186.60,204.61,187.66,146.00,US0378331005,2019-05-29T14:35:00
1,INDU:IND,INDU,Dow Jones,United States,2019-05-29T14:33:00,index,0.0,25201.43,NaN,/united-states/stock-market,...,2.1633,1855.19,7.9464,25347.77,25776.61,26592.91,24667.78,23346.24,None,2019-05-29T14:35:00

In [14]:
#To get stock market data filtered by symbols:
te.getMarketsBySymbol(symbols=['aapl:us', 'indu:ind'], output_type='raw')

[{'Symbol': 'AAPL:US',
  'Ticker': 'AAPL',
  'Name': 'Apple',
  'Country': 'United States',
  'Date': '2019-05-29T14:34:00',
  'Type': 'stocks',
  'decimals': 2.0,
  'Last': 178.9,
  'MarketCap': 1064612289.0,
  'URL': '/aapl:us',
  'Importance': 940,
  'DailyChange': 0.67,
  'DailyPercentualChange': 0.38,
  'WeeklyChange': -7.7,
  'WeeklyPercentualChange': -4.1265,
  'MonthlyChange': -25.71,
  'MonthlyPercentualChange': -12.5654,
  'YearlyChange': -8.76,
  'YearlyPercentualChange': -4.668,
  'YTDChange': 32.9,
  'YTDPercentualChange': 22.5342,
  'yesterday': 178.23,
  'lastWeek': 186.6,
  'lastMonth': 204.61,
  'lastYear': 187.66,
  'startYear': 146.0,
  'ISIN': 'US0378331005                  ',
  'LastUpdate': '2019-05-29T14:36:00'},
 {'Symbol': 'INDU:IND',
  'Ticker': 'INDU',
  'Name': 'Dow Jones',
  'Country': 'United States',
  'Date': '2019-05-29T14:34:00',
  'Type': 'index',
  'decimals': 0.0,
  'Last': 25195.43,
  'MarketCap': None,
  'URL': '/united-states/stock-market',
  'Importance': 1,
  'DailyChange': -150.34,
  'DailyPercentualChange': -0.59,
  'WeeklyChange': -581.18,
  'WeeklyPercentualChange': -2.2547,
  'MonthlyChange': -1397.48,
  'MonthlyPercentualChange': -5.2551,
  'YearlyChange': 527.65,
  'YearlyPercentualChange': 2.139,
  'YTDChange': 1849.19,
  'YTDPercentualChange': 7.9207,
  'yesterday': 25347.77,
  'lastWeek': 25776.61,
  'lastMonth': 26592.91,
  'lastYear': 24667.78,
  'startYear': 23346.24,
  'ISIN': None,
  'LastUpdate': '2019-05-29T14:36:00'}]

In [15]:
#To get closely related items of a certain symbol:
te.getMarketsPeers(symbols='indu:ind', output_type='df')

,Symbol,Ticker,Name,Country,Date,Type,decimals,Last,MarketCap,URL,...,YearlyPercentualChange,YTDChange,YTDPercentualChange,yesterday,lastWeek,lastMonth,lastYear,startYear,ISIN,LastUpdate
0,INDU:IND,INDU,Dow Jones,United States,2019-05-29T14:34:00,index,0.0,25196.43,None,/united-states/stock-market,...,2.1431,1850.190,7.9250,25347.770,25776.610,26592.910,24667.780,23346.240,None,2019-05-29T14:36:00
1,MID:IND,MID,S&P MidCap 400,United States,2019-05-29T14:14:00,index,0.0,1830.78,None,/mid:ind,...,-6.9707,172.850,10.4257,1844.170,1885.160,1970.740,1967.960,1657.930,None,2019-05-29T14:31:00
2,NDX:IND,NDX,NASDAQ 100,United States,2019-05-29T14:34:00,index,0.0,7247.79,None,/ndx:ind,...,3.8906,886.921,13.9434,7278.376,7420.656,7781.456,6976.367,6360.869,None,2019-05-29T14:36:00
3,SPX:IND,SPX,S&P 500,United States,2019-05-29T14:34:00,index,0.0,2790.30,None,/spx:ind,...,2.4335,280.270,11.1660,2802.390,2856.270,2945.830,2724.010,2510.030,None,2019-05-29T14:36:00

In [16]:
#To get closely related items of a certain group of symbols:
te.getMarketsPeers(symbols=['aapl:us', 'indu:ind'])

,Symbol,Ticker,Name,Country,Date,Type,decimals,Last,MarketCap,URL,...,YearlyPercentualChange,YTDChange,YTDPercentualChange,yesterday,lastWeek,lastMonth,lastYear,startYear,ISIN,LastUpdate
0,AAPL:US,AAPL,Apple,United States,2019-05-29T14:34:00,stocks,2.0,179.00,1.064612e+09,/aapl:us,...,-4.6147,33.000,22.6027,178.230,186.600,204.610,187.6600,146.000,US0378331005,2019-05-29T14:36:00
1,HPQ:US,HPQ,HP,United States,2019-05-29T14:34:00,stocks,2.0,19.51,4.044636e+07,/hpq:us,...,-12.0212,-1.960,-9.1290,19.660,19.440,19.660,22.1758,21.470,US40434L1052,2019-05-29T14:37:00
2,IBM:US,IBM,IBM,United States,2019-05-29T14:34:00,stocks,2.0,130.13,1.356008e+08,/ibm:us,...,-8.6999,16.430,14.4503,130.460,136.450,139.050,142.5300,113.700,US4592001014,2019-05-29T14:37:00
3,INDU:IND,INDU,Dow Jones,United States,2019-05-29T14:34:00,index,0.0,25207.41,NaN,/united-states/stock-market,...,2.1876,1861.170,7.9720,25347.770,25776.610,26592.910,24667.7800,23346.240,None,2019-05-29T14:36:00
4,MID:IND,MID,S&P MidCap 400,United States,2019-05-29T14:14:00,index,0.0,1830.78,NaN,/mid:ind,...,-6.9707,172.850,10.4257,1844.170,1885.160,1970.740,1967.9600,1657.930,None,2019-05-29T14:31:00
5,MSFT:US,MSFT,Microsoft,United States,2019-05-29T14:34:00,stocks,2.0,125.24,8.776275e+08,/msft:us,...,26.4987,25.340,25.3654,126.160,126.900,129.770,99.0050,99.900,US5949181045,2019-05-29T14:36:00
6,NDX:IND,NDX,NASDAQ 100,United States,2019-05-29T14:34:00,index,0.0,7251.54,NaN,/ndx:ind,...,3.9444,890.671,14.0023,7278.376,7420.656,7781.456,6976.3670,6360.869,None,2019-05-29T14:36:00
7,SNE:US,SNE,Sony,Japan,2019-05-28T00:00:00,stocks,2.0,49.17,7.608020e+07,/sne:us,...,4.1627,0.450,0.9236,48.980,51.030,50.250,47.2050,48.720,US8356993076,2019-05-29T09:45:00
8,SPX:IND,SPX,S&P 500,United States,2019-05-29T14:34:00,index,0.0,2791.30,NaN,/spx:ind,...,2.4703,281.270,11.2058,2802.390,2856.270,2945.830,2724.0100,2510.030,None,2019-05-29T14:36:00

In [17]:
#To get components of the certain index:
te.getMarketsComponents(symbols='psi20:ind', output_type='df')

,Symbol,Ticker,Name,Country,Date,Type,decimals,Last,MarketCap,URL,...,YearlyPercentualChange,YTDChange,YTDPercentualChange,yesterday,lastWeek,lastMonth,lastYear,startYear,ISIN,LastUpdate
0,ALTR:PL,ALTR,Altri,Portugal,2019-05-29T14:33:00,stocks,2.0,5.8500,1719705.0,/altr:pl,...,-22.7213,-0.1000,-1.6807,6.1800,6.3000,6.9850,7.5700,5.9500,PTALT0AE0002,2019-05-29T14:35:00
1,BCP:PL,BCP:PL,BCP,Portugal,2019-05-29T14:34:00,stocks,2.0,0.2544,3978537.0,/bcp:pl,...,3.1630,0.0258,11.2861,0.2572,0.2509,0.2501,0.2466,0.2286,PTBCP0AM0007,2019-05-29T14:36:00
2,COR:PL,COR:PL,Corticeira Amorim,Portugal,2019-05-29T00:00:00,stocks,2.0,10.3400,1528450.0,/cor:pl,...,-9.6154,1.2900,14.2541,10.4000,10.6400,10.7400,11.4400,9.0500,PTCOR0AE0006,2019-05-29T14:31:00
3,CTT:PL,CTT:PL,CTT,Portugal,2019-05-29T14:34:00,stocks,2.0,2.2580,505500.0,/ctt:pl,...,-17.5912,-0.7060,-23.8192,2.2980,2.2400,2.6840,2.7400,2.9640,PTCTT0AM0001,2019-05-29T14:36:00
4,EDP:PL,EDP,EDP,Portugal,2019-05-29T14:34:00,stocks,2.0,3.2820,11935374.0,/edp:pl,...,-2.1175,0.2820,9.4000,3.3710,3.2630,3.3610,3.3530,3.0000,PTEDP0AM0009,2019-05-29T14:36:00
5,EDPR:PL,EDPR,EDP Renovaveis,Spain,2019-05-29T14:34:00,stocks,2.0,8.7800,7658866.0,/edpr:pl,...,10.1631,0.9700,12.4200,8.8100,8.7600,8.8700,7.9700,7.8100,ES0127797019,2019-05-29T14:36:00
6,EGL:PL,EGL:PL,Mota Engil,Portugal,2019-05-29T14:34:00,stocks,2.0,2.0920,509449.0,/egl:pl,...,-35.2322,0.4780,29.6159,2.1080,2.1540,2.3740,3.2300,1.6140,PTMEN0AE0005,2019-05-29T14:36:00
7,GALP:PL,GALP,Galp,Portugal,2019-05-29T14:33:00,stocks,2.0,13.7100,13071351.0,/galp:pl,...,-13.1179,-0.3500,-2.4893,13.8600,14.3850,14.9700,15.7800,14.0600,PTGAL0AM0009,2019-05-29T14:35:00
8,IBS:PL,IBS,Ibersol,Portugal,2019-05-29T00:00:00,stocks,2.0,8.2000,342000.0,/ibs:pl,...,-25.7919,0.2000,2.5000,8.1600,8.1000,7.9400,11.0500,8.0000,PTIBS0AM0008,2019-05-29T14:16:00
9,JMT:PL,JMT,Jeronimo Martins,Portugal,2019-05-29T14:34:00,stocks,2.0,13.7500,7995170.0,/jmt:pl,...,1.7012,3.4500,33.4951,13.8900,13.5000,14.5200,13.5200,10.3000,PTJMT0AE0001,2019-05-29T14:36:00

In [18]:
#To get components of the group of indexes:
te.getMarketsComponents(symbols=['indu:ind', 'psi20:ind'])

,Symbol,Ticker,Name,Country,Date,Type,decimals,Last,MarketCap,URL,...,YearlyPercentualChange,YTDChange,YTDPercentualChange,yesterday,lastWeek,lastMonth,lastYear,startYear,ISIN,LastUpdate
0,AAPL:US,AAPL,Apple,United States,2019-05-29T14:35:00,stocks,2.0,178.9300,1.064612e+09,/aapl:us,...,-4.6520,32.9300,22.5548,178.2300,186.6000,204.6100,187.6600,146.0000,US0378331005,2019-05-29T14:37:00
1,ALTR:PL,ALTR,Altri,Portugal,2019-05-29T14:35:00,stocks,2.0,5.8500,1.719705e+06,/altr:pl,...,-22.7213,-0.1000,-1.6807,6.1800,6.3000,6.9850,7.5700,5.9500,PTALT0AE0002,2019-05-29T14:37:00
2,AXP:US,AXP,American Express,United States,2019-05-29T14:35:00,stocks,2.0,117.0700,9.300247e+07,/axp:us,...,18.2764,22.4100,23.6742,118.1700,120.5500,116.7600,98.9800,94.6600,US0258161092,2019-05-29T14:37:00
3,BA:US,BA,Boeing,United States,2019-05-29T14:35:00,stocks,2.0,351.2500,2.097128e+08,/ba:us,...,-1.9375,27.4400,8.4741,354.8800,358.7500,379.0500,358.1900,323.8100,US0970231058,2019-05-29T14:37:00
4,BCP:PL,BCP:PL,BCP,Portugal,2019-05-29T14:34:00,stocks,2.0,0.2544,3.978537e+06,/bcp:pl,...,3.1630,0.0258,11.2861,0.2572,0.2509,0.2501,0.2466,0.2286,PTBCP0AM0007,2019-05-29T14:36:00
5,CAT:US,CAT,Caterpillar,United States,2019-05-29T14:35:00,stocks,2.0,122.6700,9.103282e+07,/cat:us,...,-21.1936,0.6200,0.5080,121.5900,124.9500,139.0200,155.6600,122.0500,US1491231015,2019-05-29T14:37:00
6,COR:PL,COR:PL,Corticeira Amorim,Portugal,2019-05-29T00:00:00,stocks,2.0,10.3400,1.528450e+06,/cor:pl,...,-9.6154,1.2900,14.2541,10.4000,10.6400,10.7400,11.4400,9.0500,PTCOR0AE0006,2019-05-29T14:31:00
7,CSCO:US,CSCO,Cisco Systems,United States,2019-05-29T14:35:00,stocks,2.0,53.5000,2.215726e+08,/csco:us,...,24.8396,11.0000,25.8824,53.9300,56.5200,56.1300,42.8550,42.5000,US17275R1023,2019-05-29T14:37:00
8,CTT:PL,CTT:PL,CTT,Portugal,2019-05-29T14:34:00,stocks,2.0,2.2580,5.055000e+05,/ctt:pl,...,-17.5912,-0.7060,-23.8192,2.2980,2.2400,2.6840,2.7400,2.9640,PTCTT0AM0001,2019-05-29T14:36:00
9,CVX:US,CVX,Chevron,United States,2019-05-29T14:35:00,stocks,2.0,117.0500,2.363951e+08,/cvx:us,...,-6.5991,8.3000,7.6322,118.3100,121.3400,117.7200,125.3200,108.7500,US1667641005,2019-05-29T14:37:00

In [19]:
#To search markets by country.
te.getMarketsSearch(country='china')

,Symbol,Ticker,Name,Country,Date,Type,decimals,Last,MarketCap,URL,...,YearlyPercentualChange,YTDChange,YTDPercentualChange,yesterday,lastWeek,lastMonth,lastYear,startYear,ISIN,LastUpdate
0,SHCOMP:IND,SHCOMP,SHANGHAI,China,2019-05-29T06:59:00,index,0.0,2916.16455,None,/china/stock-market,...,-4.1191,450.8735,18.2889,2909.9106,2891.7046,3078.3389,3041.4434,2465.2910,None,None
1,SHSZ300:IND,SHSZ300,CSI 300,China,2019-05-29T07:00:00,index,0.0,3663.90900,None,/shsz300:ind,...,-1.5880,694.3737,23.3832,3672.2605,3649.3796,3913.2110,3723.0314,2969.5353,None,None
2,SSE50:IND,SSE50,SHANGHAI 50,China,2019-05-29T06:59:00,index,0.0,2758.21680,None,/sse50:ind,...,5.8604,495.4260,21.8945,2748.7986,2725.7344,2945.2440,2605.5220,2262.7908,None,None

In [20]:
#To search markets by country and category.
te.getMarketsSearch(country='japan', category = 'index')

,Symbol,Ticker,Name,Country,Date,Type,decimals,Last,MarketCap,URL,...,YearlyPercentualChange,YTDChange,YTDPercentualChange,yesterday,lastWeek,lastMonth,lastYear,startYear,ISIN,LastUpdate
0,NKY:IND,NKY,NIKKEI 225,Japan,2019-05-29T00:00:00,index,0.0,21003.37,None,/japan/stock-market,...,-4.6104,1441.41,7.3684,21260.14,21283.37,21923.72,22018.52,19561.96,None,None
1,VXJ:IND,VXJ,Nikkei Volatility Index,Japan,2019-05-28T00:00:00,index,2.0,17.68,None,/VXJ:IND,...,-6.4055,-9.87,-35.8258,18.12,18.37,19.43,18.89,27.55,None,None

In [21]:
#To search markets by country and categories and page number.
te.getMarketsSearch(country='japan', category = ['index', 'markets'], page = 2 )

,Symbol,Ticker,Name,Country,Date,Type,decimals,Last,MarketCap,URL,...,YearlyPercentualChange,YTDChange,YTDPercentualChange,yesterday,lastWeek,lastMonth,lastYear,startYear,ISIN,LastUpdate
0,AAXJ:US,AAXJ,iShares MSCI All Country Asia ex Japan ETF,United States,2019-04-26T17:45:00,stocks,2.0,71.99,3986916.0,/aaxj:us,...,-6.5186,3.74,5.4799,73.10,72.92,70.9600,77.010,68.25,None,None
1,CAJ:US,CAJ,Canon,Japan,2019-05-29T14:36:00,stocks,2.0,28.05,42715378.0,/caj:us,...,-17.6211,0.51,1.8519,28.15,29.37,27.7000,34.050,27.54,None,None
2,DXJ:US,DXJ,Wisdomtree Japan Hedged Equity Fund,United States,2019-05-29T14:32:00,stocks,2.0,47.85,5736276.0,/dxj:us,...,-17.8823,-2.96,-5.8256,48.80,49.03,52.6799,58.270,50.81,None,None
3,HMC:US,HMC,Honda Motor,Japan,2019-05-29T14:33:00,stocks,2.0,25.15,54950564.0,/hmc:us,...,-20.1967,-1.50,-5.6285,25.10,25.71,28.0100,31.515,26.65,None,None
4,NKY:IND,NKY,NIKKEI 225,Japan,2019-05-29T00:00:00,index,0.0,21003.37,NaN,/japan/stock-market,...,-4.6104,1441.41,7.3684,21260.14,21283.37,21923.7200,22018.520,19561.96,None,None
5,NMR:US,NMR,Nomura,Japan,2019-05-28T00:00:00,stocks,2.0,3.21,17587277.0,/nmr:us,...,-38.3877,-0.92,-22.2760,3.22,3.20,3.8000,5.210,4.13,None,None
6,SMFG:US,SMFG,Sumitomo Mitsui Financial,Japan,2019-05-28T00:00:00,stocks,2.0,7.01,56907587.0,/smfg:us,...,-15.8463,0.31,4.6269,7.04,7.02,7.2900,8.330,6.70,None,None
7,SNE:US,SNE,Sony,Japan,2019-05-28T00:00:00,stocks,2.0,49.17,76080195.0,/sne:us,...,4.1627,0.45,0.9236,48.98,51.03,50.2500,47.205,48.72,None,None
8,TM:US,TM,Toyota Motor,Japan,2019-05-29T14:35:00,stocks,2.0,119.76,203052778.0,/tm:us,...,-5.8268,3.48,2.9928,119.40,118.25,123.8100,127.170,116.28,None,None
9,VXJ:IND,VXJ,Nikkei Volatility Index,Japan,2019-05-28T00:00:00,index,2.0,17.68,NaN,/VXJ:IND,...,-6.4055,-9.87,-35.8258,18.12,18.37,19.4300,18.890,27.55,None,None

In [22]:
#To get historical market data for multiple symbols and specific time range:
te.fetchMarkets(symbol=['indu:ind', 'cl1:com'], initDate='2017-01-01', endDate='2017-06-15')

              symbol        open        high         low       close
2019-05-29  INDU:IND  25209.0801  25237.2695  25109.4199  25207.4102
2019-05-29   CL1:COM     58.8767     58.9631     57.2360     57.7802
2019-05-28   CL1:COM     58.9400     59.5700     58.1300     59.1400
2019-05-28  INDU:IND  25616.5500  25717.6300  25342.2800  25347.7700
2019-05-27   CL1:COM     58.8653     59.2640     58.1346     59.2029
2019-05-26   CL1:COM     58.8477     59.0496     58.7537     58.9439
2019-05-24   CL1:COM     58.2100     59.1000     57.5000     58.6300
2019-05-24  INDU:IND  25551.0700  25670.8100  25496.2000  25585.6900
2019-05-23  INDU:IND  25657.9900  25657.9900  25328.0900  25490.4700
2019-05-23   CL1:COM     61.3100     61.4100     57.3300     57.9100

In [23]:
#To get intraday market data for a specific symbol run:
te.getMarketsIntraday(symbols='indu:ind')

,Symbol,Date,Open,High,Low,Close
0,INDU:IND,2019-05-29T14:34:00,25198.4297,25208.4102,25198.4297,25207.4102
1,INDU:IND,2019-05-29T14:33:00,25201.4102,25202.4102,25194.4297,25197.4297
2,INDU:IND,2019-05-29T14:32:00,25199.4199,25212.4199,25199.4199,25202.4102
3,INDU:IND,2019-05-29T14:31:00,25204.4102,25204.4102,25195.4297,25200.4199
4,INDU:IND,2019-05-29T14:30:00,25199.2793,25204.4199,25191.4297,25204.4199
5,INDU:IND,2019-05-29T14:29:00,25194.2891,25201.2891,25194.2891,25198.2793
6,INDU:IND,2019-05-29T14:28:00,25178.3106,25197.2891,25178.3106,25195.2891
7,INDU:IND,2019-05-29T14:27:00,25187.3008,25194.3008,25179.3106,25179.3106
8,INDU:IND,2019-05-29T14:26:00,25191.3008,25194.3008,25183.3008,25188.3008
9,INDU:IND,2019-05-29T14:25:00,25179.3301,25191.3008,25174.3203,25190.3008

In [24]:
#To get intraday market data for a specific symbol starting on certain date and time run:
te.getMarketsIntraday(symbols='indu:ind', initDate='2018-03-13 15:30')

,Symbol,Date,Open,High,Low,Close
0,INDU:IND,2019-05-29T14:34:00,25198.4297,25208.4102,25198.4297,25207.4102
1,INDU:IND,2019-05-29T14:33:00,25201.4102,25202.4102,25194.4297,25197.4297
2,INDU:IND,2019-05-29T14:32:00,25199.4199,25212.4199,25199.4199,25202.4102
3,INDU:IND,2019-05-29T14:31:00,25204.4102,25204.4102,25195.4297,25200.4199
4,INDU:IND,2019-05-29T14:30:00,25199.2793,25204.4199,25191.4297,25204.4199
5,INDU:IND,2019-05-29T14:29:00,25194.2891,25201.2891,25194.2891,25198.2793
6,INDU:IND,2019-05-29T14:28:00,25178.3106,25197.2891,25178.3106,25195.2891
7,INDU:IND,2019-05-29T14:27:00,25187.3008,25194.3008,25179.3106,25179.3106
8,INDU:IND,2019-05-29T14:26:00,25191.3008,25194.3008,25183.3008,25188.3008
9,INDU:IND,2019-05-29T14:25:00,25179.3301,25191.3008,25174.3203,25190.3008

In [25]:
te.subscribe('EURUSD:CUR')

You are subscribed to:['EURUSD:CUR']

In [26]:
te.subscribe( ['EURUSD:CUR', 'AAPL:US', 'CL1:COM'] )
te.run(on_message)

You are subscribed to:['EURUSD:CUR', 'EURUSD:CUR', 'AAPL:US', 'CL1:COM']

NameError: name 'on_message' is not defined

In [27]:
#To get default earnings calendar:
te.getEarnings()

https://api.tradingeconomics.com/earnings/?c=guest:guest

,Date,Symbol,Name,Actual,Forecast,FiscalTag,FiscalReference,CalendarReference,Country,Currency,LastUpdate
0,2019-05-27T00:00:00,AKE:FP,Arkema,2.5,None,None,None,/,France,None,2019-05-19T00:11:00
1,2019-05-27T00:00:00,AUSS:NO,Austevoll Seafood,3.5,None,None,None,/,Norway,None,2019-05-19T00:11:00
2,2019-05-27T00:00:00,LNR:CN,Linamar,0.48,None,None,None,/,Canada,None,2019-05-19T00:11:00
3,2019-05-27T00:00:00,RUS:CN,Russel Metals,1.52,None,None,None,/,Canada,None,2019-05-19T00:11:00
4,2019-05-27T00:00:00,SAF:FP,Safran,1.82,None,None,None,/,France,None,2019-05-19T00:11:00
5,2019-05-27T00:00:00,UHR:VX,Swatch,8,None,None,None,/,Switzerland,None,2019-05-19T00:11:00
6,2019-05-27T00:00:00,1817:HK,Mulsanne Group Holding Ltd,4.39,5.88,None,None,/,Hong Kong,None,2019-05-19T12:17:00
7,2019-05-27T00:00:00,BMRI:IJ,Bank Mandiri,241.22,None,None,None,/,Indonesia,None,2019-05-21T12:12:00
8,2019-05-27T00:00:00,AMRT:IJ,Sumber Alfaria,6.24,None,None,None,/,Indonesia,None,2019-05-21T12:12:00
9,2019-05-27T00:00:00,600309:CH,Wanhua Chemical,2,None,None,None,/,China,None,2019-05-21T12:12:00

In [28]:
#To get earnings calendar by country:
te.getEarnings(country = 'united states')

https://api.tradingeconomics.com/earnings/country/united%20states?c=guest:guest

,Date,Symbol,Name,Actual,Forecast,FiscalTag,FiscalReference,CalendarReference,Country,Currency,LastUpdate
0,2019-05-28T00:00:00,CRI:US,Carters,0.5,None,None,None,/,United States,None,2019-05-22T12:12:00
1,2019-05-28T00:00:00,H:US,Hyatt Hotels,0.19,None,None,None,/,United States,None,2019-05-22T12:12:00
2,2019-05-28T00:00:00,JACK:US,Jack In The Box,0.4,None,None,None,/,United States,None,2019-05-22T12:12:00
3,2019-05-28T00:00:00,KRNY:US,Kearny Financial,0.06,None,None,None,/,United States,None,2019-05-22T12:12:00
4,2019-05-28T00:00:00,L:US,Loews,0.0625,None,None,None,/,United States,None,2019-05-22T12:12:00
5,2019-05-28T00:00:00,OMF:US,OneMain Holdings,0.25,None,None,None,/,United States,None,2019-05-22T12:12:00
6,2019-05-28T00:00:00,TER:US,Teradyne,0.09,None,None,None,/,United States,None,2019-05-22T12:12:00
7,2019-05-28T00:00:00,WLK:US,Westlake Chemical,0.25,None,None,None,/,United States,None,2019-05-22T12:12:00
8,2019-05-28T00:00:00,DWDP:US,DowDuPont Inc,1:3,None,None,None,/,United States,None,2019-05-28T16:03:00
9,2019-05-29T00:00:00,QADA:US,QAD,None,-0.08,FY2020Q1,Q1/20,2019/3,United States,USD,2019-05-28T23:13:00

In [29]:
#To get earnings calendar filtered by symbol and date:
te.getEarnings(symbols = 'msft:us', initDate='2016-01-01', endDate='2017-12-31')

https://api.tradingeconomics.com/earnings/symbol/msft%3Aus?c=guest:guest&d1=2016-01-01&d2=2017-12-31

,Date,Symbol,Name,Actual,Forecast,FiscalTag,FiscalReference,CalendarReference,Country,Currency,LastUpdate
0,2016-01-28T00:00:00,MSFT:US,Microsoft,0.78,None,FY2016Q2,Q2/16,2015/12,United States,USD,2017-08-03T21:29:00
1,2016-04-21T00:00:00,MSFT:US,Microsoft,0.62,None,FY2016Q3,Q3/16,2016/3,United States,USD,2017-08-03T21:06:00
2,2016-07-19T00:00:00,MSFT:US,Microsoft,0.69,None,FY2016Q4,Q4/16,2016/6,United States,USD,2017-08-03T16:44:00
3,2016-10-20T00:00:00,MSFT:US,Microsoft,0.76,None,FY2017Q1,Q1/17,2016/9,United States,USD,2017-08-03T15:24:00
4,2017-01-26T00:00:00,MSFT:US,Microsoft,0.84,None,FY2017Q2,Q2/17,2016/12,United States,USD,2017-08-03T13:47:00
5,2017-04-27T00:00:00,MSFT:US,Microsoft,0.73,None,FY2017Q3,Q3/17,2017/3,United States,USD,2017-08-03T11:46:00
6,2017-07-20T00:00:00,MSFT:US,Microsoft,0.98,None,FY2017Q4,Q4/17,2017/6,United States,USD,2017-08-03T10:54:00
7,2017-10-26T00:00:00,MSFT:US,Microsoft,0.84,0.72,FY2018Q1,Q1/18,2017/9,United States,USD,2017-10-26T21:08:00